### ISSUE TITLE
Error in 100.txt file?

### ISSUE THREAD

**Issue by Jahanobik234** [laboon/CS1632_Spring2018#31] opened 2018-03-09 15:33 UTC
63|206c|Cyrus>Peter(26):Mzila>Wu(35):Rana>Gaozu(14):Anne>Rana(15):SYSTEM>Peter(100)|1518893687.998872000|51d6
64|51d6|SYSTEM>Wu(100)|1518893688.8960000|7
65|7|SYSTEM>James(100)|1518893688.11869000|fec

Line 64 seems to be out of place in the 100.txt file? Sample output shows the block to be valid, but our program and investigation seems to show this to be causing an issue.

**Comment by laboon** [comment] 2018-03-09 16:40
Jonathan - Not sure what you see the problem as.  My verifier shows 100.txt as fine and I don't know what issue you are seeing - it is not obvious looking at it.

Please file this as a defect report using the standard template - description, repro steps, expected behavior, observed behavior.  Much easier for me to track down, and will be good if you ever need to describe other issues in industry or on open-source projects.  Remember that in QA vagueness is the enemy.

**Comment by Jahanobik234** [comment] 2018-03-09 17:49
Will do upon getting home from work! Are the times at this step out of order or are my eyes misleading me?

Sent from my iPhone

On Mar 9, 2018, at 11:40 AM, Bill Laboon <notifications@github.com<mailto:notifications@github.com>> wrote:


Jonathan - Not sure what you see the problem as. My verifier shows 100.txt as fine and I don't know what issue you are seeing - it is not obvious looking at it.

Please file this as a defect report using the standard template - description, repro steps, expected behavior, observed behavior. Much easier for me to track down, and will be good if you ever need to describe other issues in industry or on open-source projects. Remember that in QA vagueness is the enemy.

**Comment by Jahanobik234** [comment] 2018-03-09 18:00
My apologies Professor Laboon. My eyes glazed over it and I missed that 65 was larger. A side effect of looking at it for a while. Sorry!

Sent from my iPhone

On Mar 9, 2018, at 11:40 AM, Bill Laboon <notifications@github.com<mailto:notifications@github.com>> wrote:


Jonathan - Not sure what you see the problem as. My verifier shows 100.txt as fine and I don't know what issue you are seeing - it is not obvious looking at it.

Please file this as a defect report using the standard template - description, repro steps, expected behavior, observed behavior. Much easier for me to track down, and will be good if you ever need to describe other issues in industry or on open-source projects. Remember that in QA vagueness is the enemy.

**Comment by laboon** [comment] 2018-03-09 19:17
No worries, closing this issue.  Let me know if you have any other questions.

**Closed by laboon** 2018-03-09 19:17 UTC

**Comment by Jahanobik234** [comment] 2018-03-11 17:00
One more thing - whenever we have the flamegraph generate itself, the output is not printed to the console. It did print once, but upon running the program a few times, the output is not printed. We know that it does, so we didn't want to lose points upon grading!


Is there a fix to this?

Jonathan Hanobik


________________________________

**Comment by laboon** [comment] 2018-03-11 19:53
Not sure what the problem is in terms of output, but as long as you include the flamegraph file, you won't lose points even if it doesn't print the output.

**Comment by Jahanobik234** [comment] 2018-03-11 21:14
It seemed to only be a problem when I’m executing in GitBash, but not in Command Line. Should be OK.

Thanks!

Sent from my iPhone

On Mar 11, 2018, at 3:53 PM, Bill Laboon <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure what the problem is in terms of output, but as long as you include the flamegraph file, you won't lose points even if it doesn't print the output.
